site_name: TermuxC Wiki
site_url: https://ruizennis.github.io/TermuxC/
repo_name: Ruizennis/TermuxC
repo_url: https://github.com/Ruizennis/TermuxC
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - search.highlight
    - search.share
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - attr_list
nav:
  - Home: index.md
  - Explanation: Explanation.md

